"""
AMPL data file generation and experiment runner for NOPSOS experiments.

Two main workflows
------------------
1. General NOPSOS (core + SBS only):
      write_nopsos_dat()  ->  run_ampl()

2. Crude-oil full model (core + SBS + operational layer, MILP by default):
      crude_oil_ampl.write_crude_oil_dat()  ->  run_crude_oil_experiment()
"""

import os
import re
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from .dfa_builder import DFA


CSV_EXCLUDED_STATUSES = {
    "ampl_license_expired",
    "ampl_startup_error",
    "ampl_error",
    "timeout",
}


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class ExperimentResult:
    instance_name: str
    formulation: str          # "NOPSOS+DFA" or "SOS+RE"
    n_ops: int
    n_slots: int
    n_dfa_states: int
    n_dfa_arcs: int
    n_binary_vars: int
    n_constraints: int
    obj_value: Optional[float]
    best_bound: Optional[float]
    gap: Optional[float]
    milp_time: Optional[float]
    nlp_time: Optional[float]
    total_time: Optional[float]
    n_nodes: Optional[int]
    status: str               # "optimal", "feasible", "infeasible", "timeout", ...
    n_variables: Optional[int] = None

    def gap_pct(self):
        return 100.0 * self.gap if self.gap is not None else None

    def to_dict(self):
        d = self.__dict__.copy()
        d["gap_pct"] = self.gap_pct()
        return d


# ---------------------------------------------------------------------------
# General NOPSOS .dat writer (core + SBS, no operational layer)
# ---------------------------------------------------------------------------

def write_nopsos_dat(
    dat_path: str,
    W: List[str],
    n_slots: int,
    H: float,
    prec_edges: List[Tuple[str, str]],
    no_edges_undirected: List,
    dfa: DFA,
    extra_params: Optional[dict] = None,
    extra_sets: Optional[dict] = None,
):
    """
    Write an AMPL .dat file for nopsos.mod (core + SBS only).

    Both orientations of each undirected non-overlapping edge are written.
    """
    no_directed = set()
    for e in no_edges_undirected:
        if isinstance(e, (set, frozenset)):
            v, w = tuple(e)
        else:
            v, w = e
        no_directed.add((v, w))
        no_directed.add((w, v))

    lines = [
        "# Auto-generated by ampl_interface.write_nopsos_dat",
        f"set W := {' '.join(W)};",
        f"param n_slots := {n_slots};",
        f"param H := {H};",
        "",
    ]

    if prec_edges:
        lines.append("set PREC :=")
        for v, w in prec_edges:
            lines.append(f"  ({v}, {w})")
        lines.append(";")
    else:
        lines.append("set PREC := ;")
    lines.append("")

    if no_directed:
        lines.append("set NO :=")
        for v, w in sorted(no_directed):
            lines.append(f"  ({v}, {w})")
        lines.append(";")
    else:
        lines.append("set NO := ;")
    lines.append("")

    lines.append(f"set Q := {' '.join(str(s) for s in dfa.states)};")
    lines.append(f"param q_initial := {dfa.initial};")
    lines.append("")

    if dfa.arcs:
        lines.append("set ARCS :=")
        for a, (f, t, lab) in enumerate(dfa.arcs, start=1):
            lines.append(f"  ({a}, {f}, {t})")
        lines.append(";")
        lines.append("param arc_label :=")
        for a, (f, t, lab) in enumerate(dfa.arcs, start=1):
            lines.append(f"  [{a},{f},{t}] '{lab}'")
        lines.append(";")
    else:
        lines.append("set ARCS := ;")
    lines.append("")

    if extra_sets:
        for name, elements in extra_sets.items():
            if elements:
                lines.append(f"set {name} :=")
                for e in elements:
                    if isinstance(e, tuple):
                        lines.append(f"  ({', '.join(str(x) for x in e)})")
                    else:
                        lines.append(f"  {e}")
                lines.append(";")
            else:
                lines.append(f"set {name} := ;")

    if extra_params:
        for name, value in extra_params.items():
            if isinstance(value, dict):
                lines.append(f"param {name} :=")
                for k, v in value.items():
                    key_str = " ".join(str(x) for x in k) if isinstance(k, tuple) else str(k)
                    lines.append(f"  {key_str} {v}")
                lines.append(";")
            else:
                lines.append(f"param {name} := {value};")

    Path(dat_path).parent.mkdir(parents=True, exist_ok=True)
    with open(dat_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"[DAT] {dat_path}  |W|={len(W)} n_slots={n_slots} "
          f"DFA({dfa.n_states} states, {dfa.n_arcs} arcs)")


# ---------------------------------------------------------------------------
# AMPL run-script generators
# ---------------------------------------------------------------------------

def write_milp_run_script(
    run_path: str,
    mod_path: str,
    dat_path: str,
    sol_path: str,
    log_path: str,
    time_limit: int = 3600,
    mip_gap: float = 1e-4,
    threads: int = 1,
    extra_gurobi_opts: str = "",
    write_solution: bool = False,
    disable_sbs: bool = False,
    objective_name: str = "GrossMargin",
) -> str:
    """
    Generate the MILP step run script.

    Drops the CompositionBilinear constraint, solves with Gurobi,
    and writes the solution to sol_path for optional later use.

    disable_sbs
        When True, drop the DFA-based Symmetry Breaker System (the flow
        constraints) and fix the flow variables to zero, leaving the bare
        NOPSOS core + operational MILP.  Used for the no-SBS baseline
        configurations; the resulting model has the same optimum as the
        SBS model, so it is a pure CPU-time / node-count comparison.
    """
    log_path_opt = log_path.replace("\\", "/")
    # dualreductions=0 makes Gurobi distinguish infeasible from unbounded, so an
    # infeasible model reports solve_result "infeasible" instead of the
    # ambiguous "limit" (INF_OR_UNBD).
    gurobi_opts = (
        f"timelimit={time_limit} mipgap={mip_gap} threads={threads} "
        f"dualreductions=0 logfile='{log_path_opt}' {extra_gurobi_opts}"
    ).strip()
    gurobi_opts = gurobi_opts.replace('"', r'\"')
    solution_line = f"solution '{sol_path}';" if write_solution else ""

    # SBS off -> drop the flow layer and fix its variables to 0, leaving the bare
    #            crude-oil MILP.  FlowAssign links Z to the flow; once the flow
    #            constraints are gone the f variables are unconstrained, so we fix
    #            them to 0 to keep the branch-and-bound clean.  (The clean no-SBS
    #            comparison lives in the scheduling core, models/scheduling.mod;
    #            on the crude model this is only an ablation.)
    if disable_sbs:
        sbs_drop = (
            "drop FlowAssign;\n"
            "drop FlowStart;\n"
            "drop FlowOnePerSlot;\n"
            "drop FlowConserve;\n"
            "drop FlowEnd;\n"
            "fix {i in T, (a,q,r) in ARCS} f[i,a,q,r] := 0;\n"
        )
    else:
        sbs_drop = ""

    # AMPL takes the file name up to the first blank, so paths that contain a
    # space (e.g. a Drive folder) must be quoted; forward slashes work on Windows
    # and avoid backslash escapes inside the AMPL string.
    mod_path_q = str(mod_path).replace("\\", "/")
    dat_path_q = str(dat_path).replace("\\", "/")

    script = f"""\
# MILP step — auto-generated
reset;
model '{mod_path_q}';
data '{dat_path_q}';
drop CompositionBilinear;
{sbs_drop}objective {objective_name};
option solver gurobi;
option gurobi_options "{gurobi_opts}";
solve;
printf "===MILP_RESULT===\\n";
printf "STATUS: %s\\n", solve_result;
printf "OBJ: %.6g\\n", {objective_name};
printf "N_VARS: %d\\n", _nvars;
printf "N_CONS: %d\\n", _ncons;
printf "SOLVE_TIME: %.4f\\n", _solve_time;
printf "AMPL_TIME:  %.4f\\n", _ampl_time;
printf "===END===\\n";
{solution_line}
"""
    Path(run_path).parent.mkdir(parents=True, exist_ok=True)
    with open(run_path, "w") as fh:
        fh.write(script)
    return run_path


def write_nlp_run_script(
    run_path: str,
    mod_path: str,
    dat_path: str,
    sol_path: str,
    nlp_log_path: str,
    nlp_solver: str = "ipopt",
    nlp_time_limit: int = 600,
) -> str:
    """
    Generate the NLP step run script.

    Loads the MILP solution, fixes all binary variables, restores
    CompositionBilinear, solves with a continuous NLP solver.
    """
    nlp_opts = f"max_iter=3000 max_cpu_time={nlp_time_limit}"
    if nlp_solver.lower() == "conopt":
        nlp_opts = f"RVTIME={nlp_time_limit}"

    mod_path_q = str(mod_path).replace("\\", "/")
    dat_path_q = str(dat_path).replace("\\", "/")

    script = f"""\
# NLP step — auto-generated
reset;
model '{mod_path_q}';
data '{dat_path_q}';
restore CompositionBilinear;
solution '{sol_path}';
# Fix binary variables to MILP values
fix {{i in T, v in W}} Z[i,v];
fix {{i in T, (a,q,r) in ARCS}} f[i,a,q,r];
option solver {nlp_solver};
option {nlp_solver}_options '{nlp_opts}';
solve;
printf "===NLP_RESULT===\\n";
printf "STATUS: %s\\n", solve_result;
printf "OBJ: %.6g\\n", GrossMargin;
printf "SOLVE_TIME: %.4f\\n", _solve_time;
printf "===END===\\n";
"""
    with open(run_path, "w") as fh:
        fh.write(script)
    return run_path


# ---------------------------------------------------------------------------
# Log parsers
# ---------------------------------------------------------------------------

def parse_ampl_output(text: str, block_tag: str = "MILP_RESULT") -> dict:
    result = {
        "status": None,
        "obj": None,
        "solve_time": None,
        "ampl_time": None,
        "n_vars": None,
        "n_cons": None,
    }
    m = re.search(
        rf"==={block_tag}===(.*?)===END===", text, re.DOTALL
    )
    if not m:
        return result
    for line in m.group(1).splitlines():
        line = line.strip()
        if line.startswith("STATUS:"):
            result["status"] = line.split(":", 1)[1].strip()
        elif line.startswith("OBJ:"):
            try:
                result["obj"] = float(line.split(":", 1)[1].strip())
            except ValueError:
                pass
        elif line.startswith("SOLVE_TIME:"):
            try:
                result["solve_time"] = float(line.split(":", 1)[1].strip())
            except ValueError:
                pass
        elif line.startswith("N_VARS:"):
            try:
                result["n_vars"] = int(line.split(":", 1)[1].strip())
            except ValueError:
                pass
        elif line.startswith("N_CONS:"):
            try:
                result["n_cons"] = int(line.split(":", 1)[1].strip())
            except ValueError:
                pass
        elif line.startswith("AMPL_TIME:"):
            try:
                result["ampl_time"] = float(line.split(":", 1)[1].strip())
            except ValueError:
                pass
    return result


def classify_ampl_failure(text: str, returncode: Optional[int] = None) -> Optional[str]:
    """
    Classify AMPL failures that happen before the structured result block.
    """
    stripped = text.strip()
    lower = stripped.lower()
    if lower == "timeout":
        return "timeout"
    if (
        "license" in lower
        and any(token in lower for token in ("expired", "short term lease expired", "cannot find", "no valid"))
    ):
        return "ampl_license_expired"
    if any(token in lower for token in ("cannot execute", "can't open", "cannot open", "no such file")):
        return "ampl_startup_error"
    if returncode not in (None, 0):
        return "ampl_error"
    if stripped and "===milp_result===" not in lower and "===nlp_result===" not in lower:
        return "ampl_error"
    return None


def parse_gurobi_log(log_path: str) -> dict:
    result = {"n_nodes": None, "best_bound": None, "best_obj": None,
              "gap": None, "root_relax": None}
    if not os.path.exists(log_path):
        return result
    with open(log_path) as fh:
        text = fh.read()
    # Bound at the root node after presolve and cuts.  Absent when the model is
    # solved in presolve, in which case the caller falls back to the LP bound.
    m = re.search(r"Root relaxation: objective ([\d.eE+\-]+)", text)
    if m:
        result["root_relax"] = float(m.group(1))
    m = re.search(r"Explored (\d+) nodes", text)
    if m:
        result["n_nodes"] = int(m.group(1))
    matches = re.findall(
        r"Best objective\s+([\d.eE+\-]+),\s+best bound\s+([\d.eE+\-]+),\s+gap\s+([\d.]+)%",
        text,
    )
    if matches:
        best_obj, best_bound, gap = matches[-1]
        result["best_obj"]   = float(best_obj)
        result["best_bound"] = float(best_bound)
        result["gap"]        = float(gap) / 100.0
    return result


# ---------------------------------------------------------------------------
# Main crude-oil MILP experiment runner
# ---------------------------------------------------------------------------

def run_crude_oil_experiment(
    instance_name: str,
    formulation: str,
    mod_path: str,
    dat_path: str,
    dfa: DFA,
    W: List[str],
    n_slots: int,
    results_dir: str = "results",
    ampl_exe: str = "ampl",
    nlp_solver: str = "ipopt",
    milp_time_limit: int = 3600,
    nlp_time_limit: int = 600,
    mip_gap: float = 1e-4,
    threads: int = 1,
    run_nlp: bool = False,
    disable_sbs: bool = False,
    extra_gurobi_opts: str = "",
    objective_name: str = "GrossMargin",
) -> ExperimentResult:
    """
    Run the crude-oil MILP on a crude-oil instance.

    By default this solves only the MILP obtained by dropping
    CompositionBilinear. Set run_nlp=True to run the older second-stage NLP
    workflow without deleting the nonlinear model.

    Returns
    -------
    ExperimentResult with MILP fields populated.
    """
    os.makedirs(results_dir, exist_ok=True)
    tag = f"{instance_name}_{formulation}".replace("+", "_").replace(" ", "_")

    milp_run  = os.path.join(results_dir, f"{tag}_milp.run")
    sol_file  = os.path.join(results_dir, f"{tag}.sol")
    milp_log  = os.path.join(results_dir, f"{tag}_gurobi.log")
    milp_out  = os.path.join(results_dir, f"{tag}_milp.out")
    for stale_path in (milp_log, milp_out):
        if os.path.exists(stale_path):
            os.remove(stale_path)

    write_milp_run_script(milp_run, mod_path, dat_path, sol_file, milp_log,
                          milp_time_limit, mip_gap, threads,
                          extra_gurobi_opts=extra_gurobi_opts,
                          write_solution=run_nlp,
                          disable_sbs=disable_sbs,
                          objective_name=objective_name)

    # ── MILP step ────────────────────────────────────────────────────────────
    print(f"[MILP] {formulation} on {instance_name} ...")
    t0 = time.perf_counter()
    try:
        proc = subprocess.run(
            [ampl_exe, milp_run],
            capture_output=True, text=True,
            timeout=milp_time_limit + 120,
        )
        milp_wall = time.perf_counter() - t0
        milp_stdout = proc.stdout + proc.stderr
        milp_returncode = proc.returncode
    except subprocess.TimeoutExpired:
        milp_wall = time.perf_counter() - t0
        milp_stdout = "TIMEOUT"
        milp_returncode = None

    with open(milp_out, "w") as fh:
        fh.write(milp_stdout)

    milp_parsed = parse_ampl_output(milp_stdout, "MILP_RESULT")
    milp_failure = None if milp_parsed.get("status") else classify_ampl_failure(
        milp_stdout, milp_returncode
    )
    if milp_failure:
        milp_parsed["status"] = milp_failure
    gurobi_info = parse_gurobi_log(milp_log)
    milp_time   = milp_parsed.get("solve_time") or milp_wall

    print(f"  MILP: status={milp_parsed['status']}  "
          f"obj={milp_parsed['obj']}  time={milp_time:.1f}s  "
          f"nodes={gurobi_info.get('n_nodes')}")

    # ── NLP step (only if MILP found a feasible solution) ────────────────────
    nlp_time = None
    nlp_obj  = None
    nlp_status = "skipped"

    milp_feasible = (
        milp_parsed.get("status", "") in ("solved", "feasible", "optimal")
        and os.path.exists(sol_file)
    )

    if run_nlp and milp_feasible:
        nlp_run   = os.path.join(results_dir, f"{tag}_nlp.run")
        nlp_out   = os.path.join(results_dir, f"{tag}_nlp.out")
        nlp_log   = os.path.join(results_dir, f"{tag}_nlp.log")
        write_nlp_run_script(nlp_run, mod_path, dat_path, sol_file, nlp_log,
                             nlp_solver, nlp_time_limit)

        print(f"[NLP]  {formulation} on {instance_name} ...")
        t1 = time.perf_counter()
        try:
            proc2 = subprocess.run(
                [ampl_exe, nlp_run],
                capture_output=True, text=True,
                timeout=nlp_time_limit + 60,
            )
            nlp_wall = time.perf_counter() - t1
            nlp_stdout = proc2.stdout + proc2.stderr
            nlp_returncode = proc2.returncode
        except subprocess.TimeoutExpired:
            nlp_wall = time.perf_counter() - t1
            nlp_stdout = "TIMEOUT"
            nlp_returncode = None

        with open(nlp_out, "w") as fh:
            fh.write(nlp_stdout)

        nlp_parsed = parse_ampl_output(nlp_stdout, "NLP_RESULT")
        nlp_failure = None if nlp_parsed.get("status") else classify_ampl_failure(
            nlp_stdout, nlp_returncode
        )
        if nlp_failure:
            nlp_parsed["status"] = nlp_failure
        nlp_time   = nlp_parsed.get("solve_time") or nlp_wall
        nlp_obj    = nlp_parsed.get("obj")
        nlp_status = nlp_parsed.get("status") or "ampl_error"
        print(f"  NLP:  status={nlp_status}  obj={nlp_obj}  time={nlp_time:.1f}s")

    # Compute final gap between MILP upper bound and NLP lower bound
    milp_ub = milp_parsed.get("obj")
    gap = None
    if milp_ub is not None and nlp_obj is not None and milp_ub > 0:
        gap = abs(milp_ub - nlp_obj) / abs(milp_ub)

    n_Z = n_slots * len(W)
    n_f = n_slots * dfa.n_arcs

    return ExperimentResult(
        instance_name=instance_name,
        formulation=formulation,
        n_ops=len(W),
        n_slots=n_slots,
        n_dfa_states=dfa.n_states,
        n_dfa_arcs=dfa.n_arcs,
        n_binary_vars=n_Z + n_f,
        n_constraints=milp_parsed.get("n_cons") or 0,
        obj_value=nlp_obj if run_nlp and nlp_obj is not None else milp_ub,
        best_bound=gurobi_info.get("best_bound"),
        gap=gap if gap is not None else gurobi_info.get("gap"),
        milp_time=milp_time,
        nlp_time=nlp_time,
        total_time=(milp_time or 0) + ((nlp_time or 0) if run_nlp else 0),
        n_nodes=gurobi_info.get("n_nodes"),
        status=nlp_status if run_nlp and milp_feasible else (milp_parsed.get("status") or "ampl_error"),
        n_variables=milp_parsed.get("n_vars"),
    )


# ---------------------------------------------------------------------------
# Simpler runner for core-only experiments (no operational layer)
# ---------------------------------------------------------------------------

def run_ampl(
    instance_name: str,
    formulation: str,
    mod_path: str,
    dat_path: str,
    dfa: DFA,
    W: List[str],
    n_slots: int,
    results_dir: str = "results",
    ampl_exe: str = "ampl",
    time_limit: int = 3600,
    mip_gap: float = 1e-4,
    threads: int = 1,
) -> ExperimentResult:
    """Single-step MILP solve (for models without bilinear composition)."""
    os.makedirs(results_dir, exist_ok=True)
    tag = f"{instance_name}_{formulation}".replace("+", "_").replace(" ", "_")
    run_path = os.path.join(results_dir, f"{tag}.run")
    log_path = os.path.join(results_dir, f"{tag}_gurobi.log")
    out_path = os.path.join(results_dir, f"{tag}.out")
    sol_path = os.path.join(results_dir, f"{tag}.sol")
    for stale_path in (log_path, out_path):
        if os.path.exists(stale_path):
            os.remove(stale_path)

    log_path_opt = log_path.replace("\\", "/")
    gurobi_opts = (
        f"timelimit={time_limit} mipgap={mip_gap} threads={threads} "
        f"logfile='{log_path_opt}'"
    )
    gurobi_opts = gurobi_opts.replace('"', r'\"')
    mod_path_q = str(mod_path).replace("\\", "/")
    dat_path_q = str(dat_path).replace("\\", "/")

    script = f"""\
reset;
model '{mod_path_q}';
data '{dat_path_q}';
option solver gurobi;
option gurobi_options "{gurobi_opts}";
solve;
printf "===MILP_RESULT===\\n";
printf "STATUS: %s\\n", solve_result;
printf "OBJ: %.6g\\n", 0;
printf "N_VARS: %d\\n", _nvars;
printf "N_CONS: %d\\n", _ncons;
printf "SOLVE_TIME: %.4f\\n", _solve_time;
printf "AMPL_TIME:  %.4f\\n", _ampl_time;
printf "===END===\\n";
"""
    with open(run_path, "w") as fh:
        fh.write(script)

    print(f"[AMPL] {formulation} on {instance_name} ...")
    t0 = time.perf_counter()
    try:
        proc = subprocess.run([ampl_exe, run_path],
                              capture_output=True, text=True,
                              timeout=time_limit + 60)
        elapsed = time.perf_counter() - t0
        out = proc.stdout + proc.stderr
        returncode = proc.returncode
    except subprocess.TimeoutExpired:
        elapsed = time.perf_counter() - t0
        out = "TIMEOUT"
        returncode = None

    with open(out_path, "w") as fh:
        fh.write(out)

    parsed = parse_ampl_output(out, "MILP_RESULT")
    failure = None if parsed.get("status") else classify_ampl_failure(out, returncode)
    if failure:
        parsed["status"] = failure
    gurobi_info = parse_gurobi_log(log_path)
    solve_time = parsed.get("solve_time") or elapsed
    print(f"  status={parsed['status']}  time={solve_time:.1f}s  "
          f"nodes={gurobi_info.get('n_nodes')}")

    n_Z = n_slots * len(W)
    n_f = n_slots * dfa.n_arcs
    return ExperimentResult(
        instance_name=instance_name,
        formulation=formulation,
        n_ops=len(W),
        n_slots=n_slots,
        n_dfa_states=dfa.n_states,
        n_dfa_arcs=dfa.n_arcs,
        n_binary_vars=n_Z + n_f,
        n_constraints=parsed.get("n_cons") or 0,
        obj_value=parsed.get("obj"),
        best_bound=gurobi_info.get("best_bound"),
        gap=gurobi_info.get("gap"),
        milp_time=solve_time,
        nlp_time=None,
        total_time=solve_time,
        n_nodes=gurobi_info.get("n_nodes"),
        status=parsed.get("status") or "ampl_error",
        n_variables=parsed.get("n_vars"),
    )


# ---------------------------------------------------------------------------
# CSV export
# ---------------------------------------------------------------------------

def save_results_csv(results: List[ExperimentResult], csv_path: str):
    import csv
    results = [r for r in results if r.status not in CSV_EXCLUDED_STATUSES]
    if not results:
        print(f"[CSV] skipped {csv_path} (no successful solve results)")
        return
    file_exists = os.path.exists(csv_path)
    with open(csv_path, "a", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(results[0].to_dict().keys()))
        if not file_exists:
            writer.writeheader()
        for r in results:
            writer.writerow(r.to_dict())
    print(f"[CSV] {csv_path}")
